import { useEffect, useMemo, useState } from 'react';
import { clearWorkspace, readWorkspace, type WorkspaceTool } from './workspace';

export default function MyTooloooPanel({ tools, base }: { tools: WorkspaceTool[]; base: string }) {
  const [state, setState] = useState(() => readWorkspace());
  useEffect(() => { const sync = () => setState(readWorkspace()); window.addEventListener('khizology:toolooo:workspace', sync); return () => window.removeEventListener('khizology:toolooo:workspace', sync); }, []);
  const byId = useMemo(() => new Map(tools.map((tool) => [tool.id, tool])), [tools]);
  const favorites = state.favorites.map((id) => byId.get(id)).filter((tool): tool is WorkspaceTool => Boolean(tool));
  const recent = state.recent.map(({ toolId }) => byId.get(toolId)).filter((tool): tool is WorkspaceTool => Boolean(tool));
  if (!favorites.length && !recent.length) return null;
  const list = (items: WorkspaceTool[]) => <div style={{ display: 'grid', gap: '.45rem' }}>{items.slice(0, 5).map((tool) => <a key={tool.id} href={`${base}/toolbox/${tool.slug}`} style={{ display: 'flex', alignItems: 'center', gap: '.55rem', padding: '.5rem .6rem', textDecoration: 'none', color: 'var(--k-text)', border: '1px solid var(--k-border)', borderRadius: '.55rem', background: 'var(--k-bg)' }}><span aria-hidden="true">{tool.icon}</span><span style={{ font: '700 .76rem Poppins, sans-serif' }}>{tool.name}</span></a>)}</div>;
  return <section aria-labelledby="my-toolooo-title" style={{ background: 'var(--k-bg-card)', borderTop: '1px solid var(--k-border)', padding: '2rem 0' }}><div className="k-container"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: '1rem', flexWrap: 'wrap', marginBottom: '.9rem' }}><div><span className="k-section-label" style={{ color: '#F7933C' }}>My Toolooo</span><h2 id="my-toolooo-title" style={{ font: '800 1.2rem Poppins, sans-serif', margin: '.2rem 0', color: 'var(--k-text)' }}>Saved in this browser</h2><p style={{ margin: 0, color: 'var(--k-text-muted)', fontSize: '.8rem' }}>No signup or cloud sync. Clear it any time.</p></div><button type="button" onClick={() => { clearWorkspace(); setState(readWorkspace()); }} style={{ minHeight: 36, padding: '.4rem .7rem', border: '1px solid var(--k-border)', borderRadius: '.5rem', background: 'var(--k-bg-card)', color: 'var(--k-text-muted)', font: '700 .72rem Poppins, sans-serif', cursor: 'pointer' }}>Clear My Toolooo</button></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1rem' }}>{favorites.length > 0 && <div><h3 style={{ font: '800 .8rem Poppins, sans-serif', color: 'var(--k-text)' }}>Favorites</h3>{list(favorites)}</div>}{recent.length > 0 && <div><h3 style={{ font: '800 .8rem Poppins, sans-serif', color: 'var(--k-text)' }}>Recent</h3>{list(recent)}</div>}</div></div></section>;
}
