import { useMemo, useState, type ReactNode } from 'react';
import ShareResultFoundation from '../ShareResultFoundation';
import ToolScenarioSwitcher, { type ToolScenario } from '../lv3/ToolScenarioSwitcher';
import { trackContractDriftRun, trackToolScenarioSelect } from '../../../utils/analytics';
import { compareContractJson, driftSummary, guardrailFor, type DriftCategory, type DriftItem } from './contractDrift';

type Inputs = { expected: string; actual: string };
const examples: ToolScenario<Inputs>[] = [
  { id: 'baseline', label: 'Baseline', description: 'A stable sample with no structural change.', inputPatch: { expected: '{\n  "user": { "id": 42, "email": "a@example.com" }\n}', actual: '{\n  "user": { "id": 7, "email": "b@example.com" }\n}' } },
  { id: 'type-change', label: 'Type change', description: 'A consumer-facing identifier changes type.', inputPatch: { expected: '{\n  "user": { "id": 42, "email": "a@example.com" }\n}', actual: '{\n  "user": { "id": "42", "role": "admin" }\n}' } },
  { id: 'null-shape', label: 'Null / shape', description: 'A nullable field and array item contract change.', inputPatch: { expected: '{\n  "avatar": "https://example.com/a.png",\n  "orders": [{ "id": 1, "price": 10 }]\n}', actual: '{\n  "avatar": null,\n  "orders": [{ "id": "1", "price": 10, "coupon": "SAVE" }]\n}' } },
];
const color: Record<DriftCategory, string> = { removed: '#ef4444', 'type-change': '#ef4444', 'nullability-change': '#F7933C', 'shape-change': '#ef4444', added: '#6CA6FF', 'array-review': '#F7933C' };
const label: Record<DriftCategory, string> = { removed: 'Removed', 'type-change': 'Type change', 'nullability-change': 'Nullability change', 'shape-change': 'Shape change', added: 'Added', 'array-review': 'Array review' };
const empty: Inputs = { expected: '', actual: '' };

function inputStyle() { return { width: '100%', minHeight: 260, boxSizing: 'border-box' as const, padding: '.875rem', borderRadius: '.625rem', border: '1.5px solid var(--k-border)', background: 'var(--k-bg)', color: 'var(--k-text)', font: '.8rem "Courier New", monospace', outline: 'none', resize: 'vertical' as const }; }
function Card({ children }: { children: ReactNode }) { return <section style={{ padding: '1rem', border: '1px solid var(--k-border)', borderRadius: '.8rem', background: 'var(--k-bg-card)' }}>{children}</section>; }

export default function ApiPayloadContractDrift() {
  const [inputs, setInputs] = useState<Inputs>(empty);
  const [submitted, setSubmitted] = useState<Inputs | null>(null);
  const [activeScenario, setActiveScenario] = useState<string | null>(null);
  const [changesOnly, setChangesOnly] = useState(true);
  const [selected, setSelected] = useState<DriftItem | null>(null);
  const result = useMemo(() => submitted ? compareContractJson(submitted.expected, submitted.actual) : null, [submitted]);
  const summary = driftSummary(result?.items ?? []);
  const run = () => {
    if (!inputs.expected.trim() || !inputs.actual.trim()) return;
    const next = compareContractJson(inputs.expected, inputs.actual);
    setSubmitted(inputs); setSelected(next.items[0] ?? null);
    if (!next.expectedError && !next.actualError) trackContractDriftRun(next.items.length, driftSummary(next.items));
  };
  const applyScenario = (scenario: ToolScenario<Inputs>) => { setInputs({ ...empty, ...scenario.inputPatch }); setSubmitted(null); setSelected(null); setActiveScenario(scenario.id); trackToolScenarioSelect('api-payload-doctor', scenario.id); };
  const health = summary.likelyBreaking ? 'HIGH RISK' : summary.needsReview ? 'REVIEW' : 'STABLE';
  const guardrail = selected ? guardrailFor(selected) : null;
  const safeShare = result && !result.expectedError && !result.actualError ? { summary: `Contract Drift: ${result.items.length} structural change${result.items.length === 1 ? '' : 's'} detected — ${summary.likelyBreaking} likely breaking, ${summary.needsReview} need review, ${summary.additive} additive.` } : undefined;
  return <div style={{ display: 'grid', gap: '1rem' }}>
    <ToolScenarioSwitcher scenarios={examples} activeId={activeScenario} onSelect={applyScenario} onReset={() => { setInputs(empty); setSubmitted(null); setSelected(null); setActiveScenario(null); }} />
    <Card><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '1rem' }}>
      {(['expected', 'actual'] as const).map(side => <div key={side}><label htmlFor={`contract-${side}`} style={{ display: 'block', marginBottom: '.5rem', color: 'var(--k-text)', font: '800 .78rem Poppins, sans-serif', textTransform: 'uppercase', letterSpacing: '.06em' }}>{side}</label><textarea id={`contract-${side}`} value={inputs[side]} onChange={event => { setInputs(current => ({ ...current, [side]: event.target.value })); setActiveScenario(null); }} placeholder={`Paste ${side} JSON…`} style={inputStyle()} /></div>)}
    </div><div style={{ display: 'flex', gap: '.75rem', alignItems: 'center', flexWrap: 'wrap', marginTop: '1rem' }}><button type="button" onClick={run} disabled={!inputs.expected.trim() || !inputs.actual.trim()} style={{ minHeight: 42, border: 0, borderRadius: '.5rem', padding: '.55rem 1rem', background: inputs.expected.trim() && inputs.actual.trim() ? '#DF78A0' : 'var(--k-border)', color: '#fff', font: '800 .78rem Poppins, sans-serif', cursor: inputs.expected.trim() && inputs.actual.trim() ? 'pointer' : 'not-allowed' }}>Diagnose drift</button><span style={{ color: 'var(--k-text-muted)', fontSize: '.75rem' }}>Both payloads stay in browser memory and are never saved or shared.</span></div></Card>
    {result && <>
      {(result.expectedError || result.actualError) && <Card><strong style={{ color: '#ef4444', font: '800 .8rem Poppins, sans-serif' }}>{result.expectedError ? 'EXPECTED INVALID' : 'ACTUAL INVALID'}</strong><p style={{ margin: '.45rem 0 0', color: 'var(--k-text-muted)', fontSize: '.8rem' }}>{result.expectedError || result.actualError}</p></Card>}
      {!result.expectedError && !result.actualError && <>
        <Card><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '.75rem', flexWrap: 'wrap' }}><div><span style={{ display: 'block', color: 'var(--k-text-muted)', font: '800 .72rem Poppins, sans-serif', textTransform: 'uppercase', letterSpacing: '.06em' }}>Contract health</span><strong style={{ color: health === 'STABLE' ? '#22c55e' : health === 'REVIEW' ? '#F7933C' : '#ef4444', font: '900 1.25rem Poppins, sans-serif' }}>{health}</strong></div><div style={{ display: 'flex', gap: '.5rem', flexWrap: 'wrap' }}>{([['Likely breaking', summary.likelyBreaking, '#ef4444'], ['Need review', summary.needsReview, '#F7933C'], ['Additive', summary.additive, '#6CA6FF']] as const).map(([name, count, tone]) => <span key={name} style={{ border: `1px solid ${tone}`, color: tone, borderRadius: '999px', padding: '.3rem .55rem', font: '800 .7rem Poppins, sans-serif' }}>{count} {name}</span>)}</div></div>{result.limited && <p style={{ margin: '.75rem 0 0', color: '#F7933C', fontSize: '.78rem' }}>Large/deep payload safety limit reached: the map shows the first 1,500 structural observations.</p>}</Card>
        <Card><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '.75rem', flexWrap: 'wrap' }}><div><h3 style={{ margin: 0, color: 'var(--k-text)', font: '800 .95rem Poppins, sans-serif' }}>Visual drift map</h3><p style={{ margin: '.25rem 0 0', color: 'var(--k-text-muted)', fontSize: '.76rem' }}>Select a path to see its impact and a focused guardrail.</p></div><label style={{ display: 'flex', alignItems: 'center', gap: '.4rem', color: 'var(--k-text)', fontSize: '.76rem', fontWeight: 700 }}><input type="checkbox" checked={changesOnly} onChange={event => setChangesOnly(event.target.checked)} /> Show changes only</label></div>
          <div style={{ display: 'grid', gap: '.5rem', marginTop: '.85rem', maxHeight: 450, overflow: 'auto' }}>{(changesOnly ? result.items : result.items).length === 0 ? <p style={{ margin: 0, color: '#22c55e', fontWeight: 700 }}>No structural drift. Values changed, but the observed contract stayed compatible.</p> : result.items.map(item => <button key={`${item.path}-${item.category}`} type="button" onClick={() => setSelected(item)} aria-pressed={selected === item} style={{ textAlign: 'left', padding: '.7rem', border: `1px solid ${selected === item ? color[item.category] : 'var(--k-border)'}`, borderLeft: `5px solid ${color[item.category]}`, background: 'var(--k-bg)', borderRadius: '.5rem', color: 'var(--k-text)', cursor: 'pointer' }}><span style={{ display: 'flex', justifyContent: 'space-between', gap: '.5rem', flexWrap: 'wrap' }}><strong style={{ font: '800 .76rem Poppins, sans-serif', overflowWrap: 'anywhere' }}>{item.path}</strong><span style={{ color: color[item.category], font: '800 .68rem Poppins, sans-serif', textTransform: 'uppercase' }}>{label[item.category]} · {item.risk.replace('-', ' ')}</span></span><span style={{ display: 'block', marginTop: '.25rem', color: 'var(--k-text-muted)', font: '.75rem "Courier New", monospace' }}>{item.expected} → {item.actual}</span></button>)}</div>
        </Card>
        {selected && <Card><h3 style={{ margin: 0, color: 'var(--k-text)', font: '800 .95rem Poppins, sans-serif' }}>{selected.path}</h3><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(155px, 1fr))', gap: '.6rem', marginTop: '.75rem' }}>{[['Expected', selected.expected], ['Actual', selected.actual], ['Change', label[selected.category]]].map(([name, value]) => <div key={name} style={{ background: 'var(--k-bg)', borderRadius: '.5rem', padding: '.65rem' }}><span style={{ display: 'block', color: 'var(--k-text-muted)', font: '800 .65rem Poppins, sans-serif', textTransform: 'uppercase' }}>{name}</span><strong style={{ color: 'var(--k-text)', fontSize: '.8rem' }}>{value}</strong></div>)}</div><p style={{ margin: '.75rem 0 0', color: 'var(--k-text-muted)', fontSize: '.8rem', lineHeight: 1.55 }}><strong style={{ color: 'var(--k-text)' }}>Potential impact: </strong>{selected.impact}</p></Card>}
        {guardrail && <Card><h3 style={{ margin: 0, color: 'var(--k-text)', font: '800 .95rem Poppins, sans-serif' }}>Create guardrail</h3><p style={{ margin: '.35rem 0 .75rem', color: 'var(--k-text-muted)', fontSize: '.76rem', lineHeight: 1.5 }}>{guardrail.note}</p><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '.75rem' }}><div><strong style={{ fontSize: '.75rem', color: 'var(--k-text)' }}>JSON Schema fragment</strong><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', margin: '.4rem 0 0', padding: '.7rem', background: 'var(--k-bg)', border: '1px solid var(--k-border)', borderRadius: '.5rem', color: 'var(--k-text)', fontSize: '.7rem' }}>{guardrail.schema}</pre></div><div><strong style={{ fontSize: '.75rem', color: 'var(--k-text)' }}>Postman assertion</strong><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', margin: '.4rem 0 0', padding: '.7rem', background: 'var(--k-bg)', border: '1px solid var(--k-border)', borderRadius: '.5rem', color: 'var(--k-text)', fontSize: '.7rem' }}>{guardrail.assertion}</pre></div></div></Card>}
        <ShareResultFoundation monster="toolooo" contentType="tool" slug="api-payload-doctor" title="API Payload Doctor" result={safeShare} />
      </>}
    </>}
  </div>;
}
