import { useMemo, useState } from 'react';
import RangeControl from '../shared/RangeControl';
import Metric from '../shared/Metric';
import Insight from '../shared/Insight';
import VisualizationContainer from '../shared/VisualizationContainer';
import PresetBar from '../shared/PresetBar';
import AdvancedDisclosure from '../shared/AdvancedDisclosure';
import ShareResultFoundation from '../ShareResultFoundation';
import { simulateRate, type RateAlgorithm, type RateInputs, type TrafficPattern } from './retryRateModels';
const ACCENT = '#F7933C'; const label = { display: 'block' as const, font: '700 .76rem Poppins, sans-serif', textTransform: 'uppercase' as const, letterSpacing: '.06em', color: 'var(--k-text-muted)', marginBottom: '.4rem' };
const base: RateInputs = { rate: 20, burst: 40, algorithm: 'token-bucket', pattern: 'short-burst', rejectedRetry: false, retryDelay: 3, retryAfter: true };
const scenarios: { label: string; values: Partial<RateInputs> }[] = [
  { label: 'Current policy', values: { rate: 20, burst: 20, algorithm: 'fixed', pattern: 'short-burst', rejectedRetry: false } },
  { label: 'Balanced', values: { rate: 20, burst: 40, algorithm: 'sliding', pattern: 'sustained-overload', rejectedRetry: false } },
  { label: 'Burst-friendly', values: { rate: 20, burst: 80, algorithm: 'token-bucket', pattern: 'short-burst', rejectedRetry: false } },
  { label: 'Retry burst', values: { rate: 20, burst: 30, algorithm: 'token-bucket', pattern: 'retry-burst', rejectedRetry: true, retryAfter: true, retryDelay: 3 } },
];
export default function RateLimitPlayground() {
  const [input, setInput] = useState<RateInputs>(base); const [active, setActive] = useState<string | null>('Balanced');
  const update = <K extends keyof RateInputs>(key: K, value: RateInputs[K]) => { setInput((old) => ({ ...old, [key]: value })); setActive(null); }; const apply = (values: Partial<RateInputs>, name: string) => { setInput((old) => ({ ...old, ...values })); setActive(name); };
  const model = useMemo(() => simulateRate(input), [input]); const compare = useMemo(() => simulateRate({ ...input, rejectedRetry: false }), [input]); const max = Math.max(...model.ticks.map((tick) => tick.incoming), input.rate, 1); const w=640,h=190,bar=w/model.ticks.length;
  const action = model.totalThrottled === 0 ? 'This policy absorbs the selected traffic. Test whether that burst is legitimate before raising capacity further.' : input.rejectedRetry ? 'The rejected requests create another modeled wave. Prefer a documented Retry-After when available, and make clients back off rather than immediately retrying.' : input.pattern === 'sustained-overload' ? 'The incoming rate stays above the policy. Reduce sustained client demand or use a queue only when the system explicitly supports one.' : 'Increase burst capacity only if short spikes are legitimate; otherwise keep the policy protective and guide clients to slow down.';
  return <div style={{ background: 'var(--k-bg-card)', border: '1px solid var(--k-border)', borderRadius: '1rem', padding: '1.5rem' }}>
    <label style={label}>Rate Limit Policy Designer</label><PresetBar presets={scenarios} activeLabel={active} onSelect={apply} accent={ACCENT}/>
    <div style={{ display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:'1rem' }}><RangeControl label="Sustained policy rate" value={input.rate} onChange={(v)=>update('rate',v)} min={1} max={80} step={1} formatValue={(v)=>`${v} req/s`} accent={ACCENT}/><RangeControl label="Burst allowance" value={input.burst} onChange={(v)=>update('burst',v)} min={0} max={160} step={5} formatValue={(v)=>`${v} requests`} accent={ACCENT}/></div>
    <div style={{ margin:'1rem 0' }}><label style={label}>Limiter model</label><div style={{display:'flex',gap:'.5rem',flexWrap:'wrap'}}>{(['fixed','sliding','token-bucket'] as RateAlgorithm[]).map((item)=><button type="button" key={item} aria-pressed={input.algorithm===item} onClick={()=>update('algorithm',item)} style={{border:`1px solid ${input.algorithm===item?ACCENT:'var(--k-border)'}`,background:input.algorithm===item?`color-mix(in srgb, ${ACCENT} 12%, var(--k-bg))`:'var(--k-bg)',borderRadius:'.5rem',padding:'.45rem .7rem',font:'700 .75rem Poppins,sans-serif',color:'var(--k-text)',cursor:'pointer'}}>{item==='fixed'?'Fixed window':item==='sliding'?'Sliding window':'Token bucket'}</button>)}</div></div>
    <div style={{ margin:'1rem 0' }}><label style={label}>Traffic scenario</label><div style={{display:'flex',gap:'.5rem',flexWrap:'wrap'}}>{([['steady','Steady'],['short-burst','Short burst'],['sustained-overload','Sustained overload'],['retry-burst','Retry burst']] as [TrafficPattern,string][]).map(([value,name])=><button type="button" key={value} aria-pressed={input.pattern===value} onClick={()=>update('pattern',value)} style={{border:`1px solid ${input.pattern===value?ACCENT:'var(--k-border)'}`,background:input.pattern===value?`color-mix(in srgb, ${ACCENT} 12%, var(--k-bg))`:'var(--k-bg)',borderRadius:'.5rem',padding:'.45rem .7rem',font:'700 .75rem Poppins,sans-serif',color:'var(--k-text)',cursor:'pointer'}}>{name}</button>)}</div></div>
    <AdvancedDisclosure summary="Advanced 429 and client retry behavior"><label style={{fontSize:'.82rem',color:'var(--k-text)'}}><input type="checkbox" checked={input.rejectedRetry} onChange={(e)=>update('rejectedRetry',e.target.checked)}/> Rejected requests retry in this educational model</label><label style={{fontSize:'.82rem',color:'var(--k-text)'}}><input type="checkbox" checked={input.retryAfter} disabled={!input.rejectedRetry} onChange={(e)=>update('retryAfter',e.target.checked)}/> Model a 429 Too Many Requests response with Retry-After</label><RangeControl label="Retry-After delay" value={input.retryDelay} onChange={(v)=>update('retryDelay',v)} min={1} max={10} step={1} formatValue={(v)=>`${v} sec`} accent={ACCENT}/></AdvancedDisclosure>
    <p style={{fontSize:'.78rem',lineHeight:1.5,color:'var(--k-text-muted)'}}>Educational 24-second request-flow model. It distinguishes allowed and throttled requests; it does not imply that every limiter queues traffic or that every 429 response includes Retry-After.</p>
    <VisualizationContainer minHeight={240}><svg viewBox={`0 0 ${w} ${h+24}`} style={{width:'100%',maxWidth:`${w}px`,height:'auto'}} role="img" aria-label={`${Math.round(model.totalAllowed)} allowed and ${Math.round(model.totalThrottled)} throttled requests over 24 seconds`}><line x1="0" x2={w} y1={h-input.rate/max*h} y2={h-input.rate/max*h} stroke="var(--k-text-muted)" strokeDasharray="4 4"/>{model.ticks.map((tick,i)=><g key={i}><rect x={i*bar} y={h-tick.allowed/max*h} width={Math.max(2,bar-2)} height={tick.allowed/max*h} fill="#22c55e"/><rect x={i*bar} y={h-(tick.allowed+tick.throttled)/max*h} width={Math.max(2,bar-2)} height={tick.throttled/max*h} fill="#ef4444"/>{tick.retry>0&&<circle cx={i*bar+bar/2} cy={h-(tick.incoming/max*h)-5} r="3" fill="#6CA6FF"/>}<text x={i*bar+bar/2} y={h+14} textAnchor="middle" fontSize="8" fill="var(--k-text-muted)">{i}s</text></g>)}</svg></VisualizationContainer>
    <div style={{display:'flex',gap:'1rem',flexWrap:'wrap',fontSize:'.76rem',color:'var(--k-text-muted)',marginTop:'.6rem'}}><span>🟩 Allowed</span><span>🟥 Throttled / 429</span><span>🔵 Client retry wave</span><span>┄ Sustained rate</span></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:'.7rem',marginTop:'1rem'}}><Metric label="Allowed" value={`${Math.round(model.totalAllowed)}`} color="#22c55e"/><Metric label="Throttled / 429" value={`${Math.round(model.totalThrottled)}`} color={model.totalThrottled?'#ef4444':'#22c55e'}/><Metric label="Effective throughput" value={`${(model.totalAllowed/24).toFixed(1)} req/s`}/><Metric label="Limited time" value={`${model.limitedSeconds} sec`}/><Metric label="Client retry traffic" value={`${Math.round(model.totalRetry)}`} sublabel={input.rejectedRetry?'modeled follow-up attempts':'off'}/></div>
    <div style={{marginTop:'1rem'}}><Insight what={`${Math.round(model.totalAllowed)} requests pass and ${Math.round(model.totalThrottled)} are throttled (${model.throttlePercent.toFixed(0)}%) in this scenario.`} why={input.pattern==='short-burst'?'A short burst can fit a token reserve while the same rate sustained longer exhausts that reserve.':input.rejectedRetry?`Rejected requests add ${Math.round(model.totalRetry)} modeled follow-up attempts; ${input.retryAfter ? `the model waits ${input.retryDelay} seconds after a 429.` : 'the model uses a one-second educational retry.'}`:'Protection can be the purpose of throttling, so a larger allowed count is not automatically a better policy.'} tip={action}/></div>
    {input.rejectedRetry && <div style={{marginTop:'.8rem',fontSize:'.78rem',color:'var(--k-text-muted)'}}>Without rejected-request retries, this same policy receives {Math.round(compare.totalIncoming)} attempts instead of {Math.round(model.totalIncoming)}.</div>}
    <ShareResultFoundation monster="toolooo" contentType="tool" slug="rate-limit-playground" title="Rate Limit Playground" result={{summary:`Educational rate-limit model: ${input.algorithm}, ${input.rate} req/s sustained rate, ${input.burst} burst allowance, ${model.throttlePercent.toFixed(0)}% throttled.`}}/>
  </div>;
}
