import { useMemo, useState } from 'react';
import RangeControl from '../shared/RangeControl';
import Metric from '../shared/Metric';
import Insight from '../shared/Insight';
import VisualizationContainer from '../shared/VisualizationContainer';
import PresetBar from '../shared/PresetBar';
import AdvancedDisclosure from '../shared/AdvancedDisclosure';
import Warning from '../shared/Warning';
import ShareResultFoundation from '../ShareResultFoundation';
import { simulateRetry, type RetryInputs, type RetryStrategy, type Idempotency } from './retryRateModels';

const ACCENT = '#F7933C'; const label = { display: 'block' as const, font: '700 .76rem Poppins, sans-serif', textTransform: 'uppercase' as const, letterSpacing: '.06em', color: 'var(--k-text-muted)', marginBottom: '.4rem' };
const scenarios: { label: string; values: Partial<RetryInputs> }[] = [
  { label: 'Current · immediate', values: { originalRps: 140, failureRate: 55, failureDuration: 6, maxAttempts: 4, strategy: 'immediate', jitter: false, retryBudgetPercent: 100 } },
  { label: 'Safer · bounded jitter', values: { originalRps: 140, failureRate: 55, failureDuration: 6, maxAttempts: 3, strategy: 'exponential', initialDelay: 1, multiplier: 2, maxDelay: 8, jitter: true, retryBudgetPercent: 25 } },
  { label: 'Aggressive', values: { originalRps: 220, failureRate: 75, failureDuration: 8, maxAttempts: 6, strategy: 'immediate', jitter: false, retryBudgetPercent: 100 } },
];
const base: RetryInputs = { originalRps: 140, failureRate: 55, failureDuration: 6, maxAttempts: 4, strategy: 'immediate', initialDelay: 1, multiplier: 2, maxDelay: 8, jitter: false, retryBudgetPercent: 100, capacity: 260, errorKind: 'transient', idempotency: 'yes' };
export default function RetryStormSimulator() {
  const [input, setInput] = useState<RetryInputs>(base); const [active, setActive] = useState<string | null>('Current · immediate');
  const update = <K extends keyof RetryInputs>(key: K, value: RetryInputs[K]) => { setInput((old) => ({ ...old, [key]: value })); setActive(null); };
  const apply = (values: Partial<RetryInputs>, name: string) => { setInput((old) => ({ ...old, ...values })); setActive(name); };
  const model = useMemo(() => simulateRetry(input), [input]);
  const comparison = useMemo(() => simulateRetry({ ...input, strategy: 'exponential', jitter: true, maxAttempts: Math.min(input.maxAttempts, 3), retryBudgetPercent: Math.min(input.retryBudgetPercent, 25) }), [input]);
  const max = Math.max(...model.ticks.map((x) => x.total), input.capacity, 1); const w = 640; const h = 190; const bar = w / model.ticks.length;
  const pressure = model.pressure === 'severe' ? ['danger', 'Severe retry pressure'] as const : model.pressure === 'risk' ? ['warn', 'Recovery risk'] as const : ['good', 'Low pressure'] as const;
  const action = input.errorKind === 'non-retryable' ? 'This model treats the error as non-retryable. Resolve the request or API semantics before automating another attempt.' : input.idempotency !== 'yes' ? 'Review whether repeating this operation can repeat side effects before enabling automated retries.' : model.pressure !== 'low' ? 'Test fewer attempts, a bounded retry budget, and exponential backoff with jitter against your real dependency limits.' : 'Keep the policy bounded and test it with the API’s documented retryable errors and recovery behavior.';
  return <div style={{ background: 'var(--k-bg-card)', border: '1px solid var(--k-border)', borderRadius: '1rem', padding: '1.5rem' }}>
    <label style={label}>Retry Policy Lab</label><PresetBar presets={scenarios} activeLabel={active} onSelect={apply} accent={ACCENT} />
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))', gap: '1rem' }}>
      <RangeControl label="Original traffic" value={input.originalRps} onChange={(v) => update('originalRps', v)} min={10} max={500} step={10} formatValue={(v) => `${v} req/s`} accent={ACCENT}/>
      <RangeControl label="Failure rate during outage" value={input.failureRate} onChange={(v) => update('failureRate', v)} min={0} max={100} step={5} formatValue={(v) => `${v}%`} accent={ACCENT}/>
      <RangeControl label="Failure duration" value={input.failureDuration} onChange={(v) => update('failureDuration', v)} min={1} max={12} step={1} formatValue={(v) => `${v} sec`} accent={ACCENT}/>
    </div>
    <div style={{ margin: '1rem 0' }}><label style={label}>Backoff strategy</label><div style={{ display: 'flex', gap: '.5rem', flexWrap: 'wrap' }}>{(['immediate','fixed','exponential'] as RetryStrategy[]).map((item) => <button type="button" key={item} aria-pressed={input.strategy === item} onClick={() => update('strategy', item)} style={{ border: `1px solid ${input.strategy === item ? ACCENT : 'var(--k-border)'}`, background: input.strategy === item ? `color-mix(in srgb, ${ACCENT} 12%, var(--k-bg))` : 'var(--k-bg)', color: 'var(--k-text)', borderRadius: '.5rem', padding: '.45rem .7rem', font: '700 .75rem Poppins, sans-serif', cursor: 'pointer' }}>{item === 'immediate' ? 'Immediate' : item === 'fixed' ? 'Fixed delay' : 'Exponential'}</button>)}</div></div>
    <AdvancedDisclosure summary="Advanced retry controls"><RangeControl label="Maximum attempts" value={input.maxAttempts} onChange={(v) => update('maxAttempts', v)} min={1} max={6} step={1} formatValue={(v) => `${v} total`} accent={ACCENT}/><RangeControl label="Initial delay" value={input.initialDelay} onChange={(v) => update('initialDelay', v)} min={0} max={5} step={1} formatValue={(v) => `${v} sec`} accent={ACCENT}/><RangeControl label="Backoff multiplier" value={input.multiplier} onChange={(v) => update('multiplier', v)} min={1} max={3} step={.5} formatValue={(v) => `${v}×`} accent={ACCENT}/><RangeControl label="Maximum delay" value={input.maxDelay} onChange={(v) => update('maxDelay', v)} min={1} max={16} step={1} formatValue={(v) => `${v} sec`} accent={ACCENT}/><RangeControl label="Retry budget" value={input.retryBudgetPercent} onChange={(v) => update('retryBudgetPercent', v)} min={0} max={100} step={5} formatValue={(v) => `${v}% of original traffic`} accent={ACCENT}/><RangeControl label="Simulated capacity" value={input.capacity} onChange={(v) => update('capacity', v)} min={20} max={700} step={10} formatValue={(v) => `${v} req/s`} accent={ACCENT}/></AdvancedDisclosure>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))', gap: '.75rem', marginBottom: '1rem' }}><label style={{ fontSize: '.82rem', color: 'var(--k-text)' }}> <input type="checkbox" checked={input.jitter} disabled={input.strategy === 'immediate'} onChange={(e) => update('jitter', e.target.checked)} /> Add deterministic jitter</label><label style={{ fontSize: '.82rem', color: 'var(--k-text)' }}> Operation idempotent? <select value={input.idempotency} onChange={(e) => update('idempotency', e.target.value as Idempotency)}><option value="yes">Yes</option><option value="no">No</option><option value="unknown">Unknown</option></select></label><label style={{ fontSize: '.82rem', color: 'var(--k-text)' }}> Error type <select value={input.errorKind} onChange={(e) => update('errorKind', e.target.value as RetryInputs['errorKind'])}><option value="transient">Transient / retryable</option><option value="non-retryable">Non-retryable</option></select></label></div>
    {input.idempotency !== 'yes' && <Warning level="warn" title="Automated retries need review">Repeating this operation may repeat side effects. The simulator cannot infer idempotency.</Warning>}
    <p style={{ fontSize: '.78rem', lineHeight: 1.5, color: 'var(--k-text-muted)' }}>Educational 24-second recovery model. It sends original traffic each second, fails the configured share only during the outage, and schedules bounded retry waves. It does not reproduce a specific SDK or production dependency.</p>
    <VisualizationContainer minHeight={240}><svg viewBox={`0 0 ${w} ${h + 24}`} style={{ width: '100%', maxWidth: `${w}px`, height: 'auto' }} role="img" aria-label={`Original and retry traffic over time. Peak ${Math.round(model.peak)} requests per second, ${pressure[1].toLowerCase()}.`}><line x1="0" x2={w} y1={h - input.capacity / max * h} y2={h - input.capacity / max * h} stroke="var(--k-text-muted)" strokeDasharray="4 4"/>{model.ticks.map((tick, i) => <g key={i}><rect x={i * bar} y={h - tick.original / max * h} width={Math.max(2,bar-2)} height={tick.original / max * h} fill={ACCENT}/><rect x={i * bar} y={h - tick.total / max * h} width={Math.max(2,bar-2)} height={tick.retry / max * h} fill="#ef4444"/><text x={i*bar+bar/2} y={h+14} textAnchor="middle" fontSize="8" fill="var(--k-text-muted)">{i}s</text></g>)}</svg></VisualizationContainer>
    <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap', fontSize: '.76rem', color: 'var(--k-text-muted)', marginTop: '.6rem' }}><span>🟧 Original traffic</span><span>🟥 Retry traffic</span><span>┄ Simulated capacity</span></div>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(145px,1fr))', gap: '.7rem', marginTop: '1rem' }}><Metric label="Load amplification" value={`${model.amplification.toFixed(1)}×`} sublabel="peak vs original" color={pressure[0] === 'danger' ? '#ef4444' : pressure[0] === 'warn' ? ACCENT : '#22c55e'}/><Metric label="Retry traffic" value={`${Math.round(model.totalRetry)}`} sublabel="24-second model"/><Metric label="Peak retry wave" value={`${Math.round(model.peakRetry)} req/s`}/><Metric label="Recovery pressure" value={pressure[1]}/><Metric label="Jitter comparison" value={`${Math.round(comparison.peak)} req/s`} sublabel="bounded exponential + jitter"/></div>
    <div style={{ marginTop: '1rem' }}><Insight what={`The peak is ${Math.round(model.peak)} req/s: ${model.amplification.toFixed(1)}× the original ${input.originalRps} req/s.`} why={input.jitter ? 'Jitter spreads scheduled retries across adjacent seconds in this model, reducing synchronization; it does not guarantee a safe recovery.' : 'Without jitter, retry delays with the same policy land together more easily, producing visible waves in this model.'} tip={action}/></div>
    <ShareResultFoundation monster="toolooo" contentType="tool" slug="retry-storm-simulator" title="Retry Storm Simulator" result={{ summary: `Educational retry model: ${input.strategy}${input.jitter ? ' + jitter' : ''}, ${input.maxAttempts} total attempts, ${model.amplification.toFixed(1)}× peak load amplification and ${Math.round(model.peakRetry)} req/s peak retry traffic.` }}/>
  </div>;
}
