import { useMemo, useState, type CSSProperties, type ReactNode } from 'react';
import type { InfoooEntity, InfoooKnowledge, InfoooLayer, InfoooMode, InfoooRelationship, InfoooWorld } from '../../data/infooo';

const accent = 'var(--infooo-accent, #5CCFAF)';
const card = { background: 'var(--k-bg-card)', border: '1px solid var(--k-border)', borderRadius: '1rem' } as const;

export function InfoooWorldShell({ world, stage, controls, details }: { world: InfoooWorld; stage: ReactNode; controls?: ReactNode; details?: ReactNode }) {
  return <main aria-label={`${world.title} interactive knowledge world`} style={{ '--infooo-accent': world.accent || '#5CCFAF', display: 'grid', gap: '1rem', gridTemplateColumns: 'minmax(0, 1fr)', maxWidth: 1440, margin: '0 auto', padding: '1rem' } as CSSProperties}>
    <header style={{ display: 'flex', gap: '.75rem', justifyContent: 'space-between', alignItems: 'baseline', flexWrap: 'wrap' }}><div><p style={{ color: accent, font: '800 .72rem Poppins, sans-serif', letterSpacing: '.08em', margin: 0 }}>INFOOO · WORLD {String(world.worldNumber).padStart(3, '0')}</p><h1 style={{ margin: '.2rem 0 0', fontFamily: 'Poppins, sans-serif' }}>{world.title}</h1></div>{controls}</header>
    <section style={{ display: 'grid', gap: '1rem', gridTemplateColumns: 'minmax(0, 1fr)' }}>{stage}{details}</section>
  </main>;
}

export function InfoooStage({ label = 'Interactive world', children }: { label?: string; children: ReactNode }) { return <section aria-label={label} style={{ ...card, minHeight: 'min(68vh, 760px)', padding: '1rem', position: 'relative', overflow: 'hidden' }}>{children}</section>; }
export function InfoooToolbar({ children }: { children: ReactNode }) { return <nav aria-label="World controls" style={{ ...card, padding: '.625rem', display: 'flex', gap: '.5rem', flexWrap: 'wrap' }}>{children}</nav>; }
export function InfoooLayerControl({ layers, activeId, onSelect }: { layers: InfoooLayer[]; activeId?: string; onSelect: (id: string) => void }) { if (!layers.length) return null; return <div role="group" aria-label="World layers" style={{ display: 'flex', gap: '.4rem', flexWrap: 'wrap' }}>{layers.map(layer => <button key={layer.id} type="button" aria-pressed={activeId === layer.id} onClick={() => onSelect(layer.id)} style={{ border: `1px solid ${accent}`, borderRadius: '999px', background: activeId === layer.id ? accent : 'transparent', color: 'var(--k-text)', padding: '.4rem .65rem', fontWeight: 700 }}>{layer.label}</button>)}</div>; }
export function InfoooModeSwitcher({ modes, activeMode, onSelect }: { modes: InfoooMode[]; activeMode?: InfoooMode; onSelect: (mode: InfoooMode) => void }) { if (!modes.length) return null; return <div role="tablist" aria-label="Learning mode" style={{ display: 'flex', gap: '.4rem', flexWrap: 'wrap' }}>{modes.map(mode => <button key={mode} type="button" role="tab" aria-selected={activeMode === mode} onClick={() => onSelect(mode)} style={{ border: '1px solid var(--k-border)', borderRadius: '.6rem', background: activeMode === mode ? 'color-mix(in srgb, #5CCFAF 22%, var(--k-bg-card))' : 'var(--k-bg-card)', color: 'var(--k-text)', padding: '.4rem .65rem', fontWeight: 700, textTransform: 'capitalize' }}>{mode.replace('-', ' ')}</button>)}</div>; }
export function InfoooEntityPanel({ entities, selectedId, onSelect }: { entities: InfoooEntity[]; selectedId?: string; onSelect: (id: string) => void }) { const [query, setQuery] = useState(''); const matches = useMemo(() => entities.filter(entity => entity.title.toLowerCase().includes(query.toLowerCase())), [entities, query]); return <aside aria-label="World entities" style={{ ...card, padding: '1rem' }}><label style={{ display: 'grid', gap: '.35rem', fontWeight: 700 }}>Find an object<input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search this world" style={{ border: '1px solid var(--k-border)', borderRadius: '.6rem', padding: '.55rem', background: 'var(--k-bg)', color: 'var(--k-text)' }} /></label><div role="list" style={{ display: 'grid', gap: '.4rem', marginTop: '.75rem' }}>{matches.map(entity => <button key={entity.id} type="button" role="listitem" aria-pressed={selectedId === entity.id} onClick={() => onSelect(entity.id)} style={{ textAlign: 'left', border: '1px solid var(--k-border)', borderRadius: '.6rem', padding: '.55rem', background: selectedId === entity.id ? 'color-mix(in srgb, #5CCFAF 18%, var(--k-bg-card))' : 'var(--k-bg-card)', color: 'var(--k-text)' }}>{entity.shortTitle || entity.title}</button>)}</div></aside>; }
export function InfoooKnowledgePanel({ entity, knowledge }: { entity?: InfoooEntity; knowledge?: InfoooKnowledge }) { if (!entity || !knowledge) return null; const entries = [['What it is', knowledge.whatIs || knowledge.shortExplanation], ['Where it is', knowledge.whereIs], ['How it works', knowledge.howItWorks], ['Why it matters', knowledge.whyItMatters]].filter((entry): entry is [string, string] => Boolean(entry[1])); return <aside aria-live="polite" aria-label="Selected knowledge" style={{ ...card, padding: '1rem' }}><h2 style={{ margin: 0 }}>{entity.title}</h2>{entries.map(([label, copy]) => <section key={label}><h3 style={{ color: accent, font: '800 .72rem Poppins, sans-serif', letterSpacing: '.06em', margin: '.9rem 0 .15rem' }}>{label}</h3><p style={{ margin: 0, color: 'var(--k-text-muted)' }}>{copy}</p></section>)}</aside>; }
export function InfoooRelationshipPanel({ relationships, selectedId }: { relationships: InfoooRelationship[]; selectedId?: string }) { const relevant = selectedId ? relationships.filter(item => item.from === selectedId || item.to === selectedId) : relationships; if (!relevant.length) return null; const srOnly = { position: 'absolute', width: 1, height: 1, padding: 0, margin: -1, overflow: 'hidden', clip: 'rect(0, 0, 0, 0)', whiteSpace: 'nowrap', border: 0 } as CSSProperties; return <section aria-label="Relationships" style={{ ...card, padding: '1rem' }}><h2 style={{ marginTop: 0 }}>Connections</h2>{relevant.map(item => <p key={item.id} style={{ margin: '.55rem 0', color: 'var(--k-text-muted)' }}><strong style={{ color: 'var(--k-text)' }}>{item.from}</strong> <span aria-hidden="true">→</span><span style={srOnly}> {item.type.replace('-', ' ')} </span><strong style={{ color: 'var(--k-text)' }}>{item.to}</strong>: {item.explanation}</p>)}</section>; }
export function InfoooLoadingState({ message = 'Preparing the world…' }: { message?: string }) { return <div role="status" aria-live="polite" style={{ ...card, minHeight: 180, display: 'grid', placeItems: 'center', padding: '1rem', color: 'var(--k-text-muted)', fontFamily: 'Poppins, sans-serif', fontWeight: 700 }}>{message}</div>; }
export function InfoooSourceDisclosure({ knowledge }: { knowledge?: InfoooKnowledge }) { const sources = knowledge?.sources?.filter(source => source.label && source.url) || []; const rows = [['Fact', knowledge?.fact], ['Model', knowledge?.model], ['Simulation', knowledge?.simulation], ['Limitations', knowledge?.limitations], ['Educational context', knowledge?.educationalContext], ['Last reviewed', knowledge?.lastReviewed]].filter((row): row is [string, string] => Boolean(row[1])); if (!rows.length && !sources.length) return null; return <details style={{ ...card, padding: '1rem' }}><summary style={{ cursor: 'pointer', fontWeight: 800 }}>How this world stays honest</summary>{rows.map(([label, value]) => <p key={label} style={{ color: 'var(--k-text-muted)' }}><strong style={{ color: 'var(--k-text)' }}>{label}:</strong> {value}</p>)}{sources.length > 0 && <ul>{sources.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label}</a></li>)}</ul>}</details>; }
